<link media="all" type="text/css" href="<?php echo PUBLIC_CSS ?>includes/tag.css?ver=4.4" id="dashicons-css" rel="stylesheet" />

<div style="width:74.4%; text-align: justify;" class="column" id="ja-current-content">
    <div class="ja-content-main clearfix" id="ja-content-main" style="padding-bottom: 10px;">
        <?php
        if (isset($this->attractionBO) && $this->attractionBO != NULL) {

            ?>
            <div itemtype="http://schema.org/Article" itemscope="" class="item-page">
                <h1 class="contentheading2 clearfix"><?php echo $this->attractionBO->name; ?></h1>
                <div class="article-content">
                </div>
            </div>

            <div class="article-tools clearfix">                    
                <div class="size-1 extravote">
                    <span itemtype="/AggregateRating" itemscope="" itemprop="aggregateRating" class="extravote-stars">
                        <meta content="2" itemprop="ratingCount">
                        <span itemprop="ratingValue" style="width:<?php
                        if (isset($this->attractionBO->current_rating) && is_numeric($this->attractionBO->current_rating)) {
                            echo $this->attractionBO->current_rating * 100 / 5;
                        } else {
                            echo 0;
                        }

                        ?>%;" class="current-rating" id="rating_623_0"><?php
                              if (isset($this->attractionBO->current_rating) && is_numeric($this->attractionBO->current_rating)) {
                                  echo $this->attractionBO->current_rating;
                              } else {
                                  echo 0;
                              }

                              ?></span>
                        <span class="extravote-star"><a class="ev-5-stars" title="0.5 out of 5" onclick="javascript:JVXVote(623, 0.5, 8, 2, '0', 1, 1, 1);" href="">1</a></span>
                        <span class="extravote-star"><a class="ev-10-stars" title="1 out of 5" onclick="javascript:JVXVote(623, 1, 8, 2, '0', 1, 1, 1);" href="">1</a></span>
                        <span class="extravote-star"><a class="ev-15-stars" title="1.5 out of 5" onclick="javascript:JVXVote(623, 1.5, 8, 2, '0', 1, 1, 1);" href="">1</a></span>
                        <span class="extravote-star"><a class="ev-20-stars" title="2 out of 5" onclick="javascript:JVXVote(623, 2, 8, 2, '0', 1, 1, 1);" href="">1</a></span>
                        <span class="extravote-star"><a class="ev-25-stars" title="2.5 out of 5" onclick="javascript:JVXVote(623, 2.5, 8, 2, '0', 1, 1, 1);" href="">1</a></span>
                        <span class="extravote-star"><a class="ev-30-stars" title="3 out of 5" onclick="javascript:JVXVote(623, 3, 8, 2, '0', 1, 1, 1);" href="">1</a></span>
                        <span class="extravote-star"><a class="ev-35-stars" title="3.5 out of 5" onclick="javascript:JVXVote(623, 3.5, 8, 2, '0', 1, 1, 1);" href="">1</a></span>
                        <span class="extravote-star"><a class="ev-40-stars" title="4 out of 5" onclick="javascript:JVXVote(623, 4, 8, 2, '0', 1, 1, 1);" href="">1</a></span>
                        <span class="extravote-star"><a class="ev-45-stars" title="4.5 out of 5" onclick="javascript:JVXVote(623, 4.5, 8, 2, '0', 1, 1, 1);" href="">1</a></span>
                        <span class="extravote-star"><a class="ev-50-stars" title="5 out of 5" onclick="javascript:JVXVote(623, 5, 8, 2, '0', 1, 1, 1);" href="">1</a></span>
                    </span>
                    <span id="extravote_623_0" class="extravote-info">Rating <?php
                        if (isset($this->attractionBO->current_rating) && is_numeric($this->attractionBO->current_rating)) {
                            echo $this->attractionBO->current_rating;
                        } else {
                            echo 0;
                        }

                        ?> (<?php
                        if (isset($this->attractionBO->vote_times)) {
                            echo $this->attractionBO->vote_times;
                        } else {
                            echo 0;
                        }

                        ?> Votes)</span>
                </div>
            </div>

            <?php
            if (isset($this->attractionBO->post_content_1)) {
                echo str_replace("\n", "<br>", $this->attractionBO->post_content_1);
            }
            if (isset($this->attractionBO->images)) {

                ?>

                <!-- #region Jssor Slider Begin -->

                <!-- Generated by Jssor Slider Maker Online. -->
                <!-- This demo works without jquery library. -->

                <script type="text/javascript" src="<?php echo PUBLIC_JS; ?>includes/slider/jssor.slider.min.js"></script>
                <!-- use jssor.slider.debug.js instead for debug -->
                <script>
                            jssor_1_slider_init = function () {

                                var jssor_1_SlideshowTransitions = [
                                    {$Duration: 1200, x: 0.3, $During: {$Left: [0.3, 0.7]}, $Easing: {$Left: $Jease$.$InCubic, $Opacity: $Jease$.$Linear}, $Opacity: 2},
                                    {$Duration: 1200, x: -0.3, $SlideOut: true, $Easing: {$Left: $Jease$.$InCubic, $Opacity: $Jease$.$Linear}, $Opacity: 2},
                                    {$Duration: 1200, x: -0.3, $During: {$Left: [0.3, 0.7]}, $Easing: {$Left: $Jease$.$InCubic, $Opacity: $Jease$.$Linear}, $Opacity: 2},
                                    {$Duration: 1200, x: 0.3, $SlideOut: true, $Easing: {$Left: $Jease$.$InCubic, $Opacity: $Jease$.$Linear}, $Opacity: 2},
                                    {$Duration: 1200, y: 0.3, $During: {$Top: [0.3, 0.7]}, $Easing: {$Top: $Jease$.$InCubic, $Opacity: $Jease$.$Linear}, $Opacity: 2},
                                    {$Duration: 1200, y: -0.3, $SlideOut: true, $Easing: {$Top: $Jease$.$InCubic, $Opacity: $Jease$.$Linear}, $Opacity: 2},
                                    {$Duration: 1200, y: -0.3, $During: {$Top: [0.3, 0.7]}, $Easing: {$Top: $Jease$.$InCubic, $Opacity: $Jease$.$Linear}, $Opacity: 2},
                                    {$Duration: 1200, y: 0.3, $SlideOut: true, $Easing: {$Top: $Jease$.$InCubic, $Opacity: $Jease$.$Linear}, $Opacity: 2},
                                    {$Duration: 1200, x: 0.3, $Cols: 2, $During: {$Left: [0.3, 0.7]}, $ChessMode: {$Column: 3}, $Easing: {$Left: $Jease$.$InCubic, $Opacity: $Jease$.$Linear}, $Opacity: 2},
                                    {$Duration: 1200, x: 0.3, $Cols: 2, $SlideOut: true, $ChessMode: {$Column: 3}, $Easing: {$Left: $Jease$.$InCubic, $Opacity: $Jease$.$Linear}, $Opacity: 2},
                                    {$Duration: 1200, y: 0.3, $Rows: 2, $During: {$Top: [0.3, 0.7]}, $ChessMode: {$Row: 12}, $Easing: {$Top: $Jease$.$InCubic, $Opacity: $Jease$.$Linear}, $Opacity: 2},
                                    {$Duration: 1200, y: 0.3, $Rows: 2, $SlideOut: true, $ChessMode: {$Row: 12}, $Easing: {$Top: $Jease$.$InCubic, $Opacity: $Jease$.$Linear}, $Opacity: 2},
                                    {$Duration: 1200, y: 0.3, $Cols: 2, $During: {$Top: [0.3, 0.7]}, $ChessMode: {$Column: 12}, $Easing: {$Top: $Jease$.$InCubic, $Opacity: $Jease$.$Linear}, $Opacity: 2},
                                    {$Duration: 1200, y: -0.3, $Cols: 2, $SlideOut: true, $ChessMode: {$Column: 12}, $Easing: {$Top: $Jease$.$InCubic, $Opacity: $Jease$.$Linear}, $Opacity: 2},
                                    {$Duration: 1200, x: 0.3, $Rows: 2, $During: {$Left: [0.3, 0.7]}, $ChessMode: {$Row: 3}, $Easing: {$Left: $Jease$.$InCubic, $Opacity: $Jease$.$Linear}, $Opacity: 2},
                                    {$Duration: 1200, x: -0.3, $Rows: 2, $SlideOut: true, $ChessMode: {$Row: 3}, $Easing: {$Left: $Jease$.$InCubic, $Opacity: $Jease$.$Linear}, $Opacity: 2},
                                    {$Duration: 1200, x: 0.3, y: 0.3, $Cols: 2, $Rows: 2, $During: {$Left: [0.3, 0.7], $Top: [0.3, 0.7]}, $ChessMode: {$Column: 3, $Row: 12}, $Easing: {$Left: $Jease$.$InCubic, $Top: $Jease$.$InCubic, $Opacity: $Jease$.$Linear}, $Opacity: 2},
                                    {$Duration: 1200, x: 0.3, y: 0.3, $Cols: 2, $Rows: 2, $During: {$Left: [0.3, 0.7], $Top: [0.3, 0.7]}, $SlideOut: true, $ChessMode: {$Column: 3, $Row: 12}, $Easing: {$Left: $Jease$.$InCubic, $Top: $Jease$.$InCubic, $Opacity: $Jease$.$Linear}, $Opacity: 2},
                                    {$Duration: 1200, $Delay: 20, $Clip: 3, $Assembly: 260, $Easing: {$Clip: $Jease$.$InCubic, $Opacity: $Jease$.$Linear}, $Opacity: 2},
                                    {$Duration: 1200, $Delay: 20, $Clip: 3, $SlideOut: true, $Assembly: 260, $Easing: {$Clip: $Jease$.$OutCubic, $Opacity: $Jease$.$Linear}, $Opacity: 2},
                                    {$Duration: 1200, $Delay: 20, $Clip: 12, $Assembly: 260, $Easing: {$Clip: $Jease$.$InCubic, $Opacity: $Jease$.$Linear}, $Opacity: 2},
                                    {$Duration: 1200, $Delay: 20, $Clip: 12, $SlideOut: true, $Assembly: 260, $Easing: {$Clip: $Jease$.$OutCubic, $Opacity: $Jease$.$Linear}, $Opacity: 2}
                                ];

                                var jssor_1_options = {
                                    $AutoPlay: true,
                                    $SlideshowOptions: {
                                        $Class: $JssorSlideshowRunner$,
                                        $Transitions: jssor_1_SlideshowTransitions,
                                        $TransitionsOrder: 1
                                    },
                                    $ArrowNavigatorOptions: {
                                        $Class: $JssorArrowNavigator$
                                    },
                                    $ThumbnailNavigatorOptions: {
                                        $Class: $JssorThumbnailNavigator$,
                                        $Cols: 10,
                                        $SpacingX: 8,
                                        $SpacingY: 8,
                                        $Align: 360
                                    }
                                };

                                var jssor_1_slider = new $JssorSlider$("jssor_1", jssor_1_options);

                                //responsive code begin
                                //you can remove responsive code if you don't want the slider scales while window resizing
                                function ScaleSlider() {
                                    var refSize = jssor_1_slider.$Elmt.parentNode.clientWidth;
                                    if (refSize) {
                                        refSize = Math.min(refSize, 800);
                                        jssor_1_slider.$ScaleWidth(refSize);
                                    }
                                    else {
                                        window.setTimeout(ScaleSlider, 30);
                                    }
                                }
                                ScaleSlider();
                                $Jssor$.$AddEvent(window, "load", ScaleSlider);
                                $Jssor$.$AddEvent(window, "resize", ScaleSlider);
                                $Jssor$.$AddEvent(window, "orientationchange", ScaleSlider);
                                //responsive code end
                            };
                </script>

                <style>

                    /* jssor slider arrow navigator skin 05 css */
                    /*
                    .jssora05l                  (normal)
                    .jssora05r                  (normal)
                    .jssora05l:hover            (normal mouseover)
                    .jssora05r:hover            (normal mouseover)
                    .jssora05l.jssora05ldn      (mousedown)
                    .jssora05r.jssora05rdn      (mousedown)
                    */
                    .jssora05l, .jssora05r {
                        display: block;
                        position: absolute;
                        /* size of arrow element */
                        width: 40px;
                        height: 40px;
                        cursor: pointer;
                        background: url('<?php echo PUBLIC_IMG; ?>icon/a17.png') no-repeat;
                        overflow: hidden;
                    }
                    .jssora05l { background-position: -10px -40px; }
                    .jssora05r { background-position: -70px -40px; }
                    .jssora05l:hover { background-position: -130px -40px; }
                    .jssora05r:hover { background-position: -190px -40px; }
                    .jssora05l.jssora05ldn { background-position: -250px -40px; }
                    .jssora05r.jssora05rdn { background-position: -310px -40px; }

                    /* jssor slider thumbnail navigator skin 01 css */
                    /*
                    .jssort01 .p            (normal)
                    .jssort01 .p:hover      (normal mouseover)
                    .jssort01 .p.pav        (active)
                    .jssort01 .p.pdn        (mousedown)
                    */
                    .jssort01 .p {
                        position: absolute;
                        top: 0;
                        left: 0;
                        width: 162px;
                        height: 72px;
                    }

                    .jssort01 .t {
                        position: absolute;
                        top: 0;
                        left: 0;
                        width: 100%;
                        height: 100%;
                        border: none;
                    }

                    .jssort01 .w {
                        position: absolute;
                        top: 0px;
                        left: 0px;
                        width: 100%;
                        height: 100%;
                    }

                    .jssort01 .c {
                        position: absolute;
                        top: 0px;
                        left: 0px;
                        width: 158px;
                        height: 68px;
                        border: #000 2px solid;
                        box-sizing: content-box;
                        background: url('<?php echo PUBLIC_IMG; ?>icon/t01.png') -800px -800px no-repeat;
                        _background: none;
                    }

                    .jssort01 .pav .c {
                        top: 2px;
                        _top: 0px;
                        left: 2px;
                        _left: 0px;
                        width: 158px;
                        height: 68px;
                        border: #000 0px solid;
                        _border: #fff 2px solid;
                        background-position: 50% 50%;
                    }

                    .jssort01 .p:hover .c {
                        top: 0px;
                        left: 0px;
                        width: 160px;
                        height: 70px;
                        border: #fff 1px solid;
                        background-position: 50% 50%;
                    }

                    .jssort01 .p.pdn .c {
                        background-position: 50% 50%;
                        width: 158px;
                        height: 68px;
                        border: #000 2px solid;
                    }

                    * html .jssort01 .c, * html .jssort01 .pdn .c, * html .jssort01 .pav .c {
                        /* ie quirks mode adjust */
                        width /**/: 162px;
                        height /**/: 72px;
                    }

                </style>
                <div style="margin: 10px auto;">
                    <div id="jssor_1" style="position: relative; margin: 0 auto; top: 0px; left: 0px; width: 800px; height: 456px; overflow: hidden; visibility: hidden; background-color: #24262e;">
                        <!-- Loading Screen -->
                        <div data-u="loading" style="position: absolute; top: 0px; left: 0px;">
                            <div style="filter: alpha(opacity=70); opacity: 0.7; position: absolute; display: block; top: 0px; left: 0px; width: 100%; height: 100%;"></div>
                            <div style="position:absolute;display:block;background:url('<?php echo PUBLIC_IMG; ?>icon/loading.gif') no-repeat center center;top:0px;left:0px;width:100%;height:100%;"></div>
                        </div>
                        <div data-u="slides" style="cursor: default; position: relative; top: 0px; left: 0px; width: 800px; height: 356px; overflow: hidden;">
                            <?php
                            if (isset($this->attractionBO->images)) {
                                foreach ($this->attractionBO->images as $image) {
                                    if (isset($image->image_url)) {

                                        ?>
                                        <div data-p="144.50" style="display: none;">
                                            <img data-u="image" src="<?php echo URL . $image->large_url; ?>" />
                                            <img data-u="thumb" src="<?php echo URL . $image->slider_thumb_url; ?>" />
                                        </div>

                                        <?php
                                    }
                                }
                            }

                            ?>                    
                        </div>
                        <!-- Thumbnail Navigator -->
                        <div data-u="thumbnavigator" class="jssort01" style="position:absolute;left:0px;bottom:0px;width:800px;height:100px;" data-autocenter="1">
                            <!-- Thumbnail Item Skin Begin -->
                            <div data-u="slides" style="cursor: default;">
                                <div data-u="prototype" class="p">
                                    <div class="w">
                                        <div data-u="thumbnailtemplate" class="t"></div>
                                    </div>
                                    <div class="c"></div>
                                </div>
                            </div>
                            <!-- Thumbnail Item Skin End -->
                        </div>
                        <!-- Arrow Navigator -->
                        <span data-u="arrowleft" class="jssora05l" style="top:158px;left:8px;width:40px;height:40px;"></span>
                        <span data-u="arrowright" class="jssora05r" style="top:158px;right:8px;width:40px;height:40px;"></span>
                        <a href="http://www.jssor.com" style="display:none">Slideshow Maker</a>
                    </div>
                </div>

                <script>
                    jssor_1_slider_init();
                </script>

                <!-- #endregion Jssor Slider End -->

                <?php
            }
            if (isset($this->attractionBO->post_content_2)) {
                echo str_replace("\n", "<br>", $this->attractionBO->post_content_2);
            }

            if (isset($this->attractionBO->tag_list) && count($this->attractionBO->tag_list) > 0) {

                ?>
                <div style="margin-top: 10px;">
                    <strong><?php echo TAGS_TITLE ?></strong>: 
                    <ul class="tagList">
                        <?php
                        $tagArray = array();
                        foreach ($this->attractionBO->tag_list as $tag) {
                            $tagArray[] = $tag->name;

                            ?>
                            <li style="background: transparent none repeat scroll 0% 0%; padding-left: 10px;"><a class="tag" href="<?php echo URL . CONTEXT_PATH_TAG_INFO . $tag->term_taxonomy_id . "/" . $tag->slug; ?>/" title=""><span class="arrow2"></span><?php echo $tag->name; ?></a></li>
                                    <?php
                                }

                                ?>
                    </ul>
                </div>
                <br>
                <?php
            }

            ?>

            <?php
        } else {
            $this->renderFeedbackMessages();
        }

        ?>
    </div>
</div>

<?php
$module = array("findTours", "destinationsVietnam", "aboutVietnam", "destinationsVietnam");
require VIEW_TEMPLATES_PATH . 'loadModule.php';

?>


